export const brand = {
  velvet: "#6C1D5F",
  velvetDark: "#4A1E47",
  brightVelvet: "#84117C",
  teal: "#01AC9F",
  orange: "#FF6200",
  grey: "#5A5A5A",
  lightGrey: "#DEDEDE",
  blueGrey: "#F7F8FC",
  mediumBlueGrey: "#DADCEA"
};

export const levels = ["Beginner", "Intermediate", "Advanced", "Expert"];
export const blockTypes = ["Heading", "Text", "Code", "Video", "Image", "Callout", "Table", "PDF", "PPT", "Notes"];

export { createSlug as slugify } from "./slug.utils.js";
export { createId as uid } from "./id.utils.js";

export const seedState = {
  categories: [
    {
      id: "cat-web",
      name: "Web Development",
      slug: "web-development",
      iconType: "emoji",
      icon: "💻",
      imageUrl: "",
      description: "Frontend, backend and full-stack web technologies.",
      accentColor: "#01AC9F",
      status: "Active",
      courses: 24,
      learners: 1840
    },
    {
      id: "cat-cloud",
      name: "Cloud & DevOps",
      slug: "cloud-devops",
      iconType: "emoji",
      icon: "☁️",
      imageUrl: "",
      description: "AWS, GCP, Kubernetes, CI/CD and infrastructure.",
      accentColor: "#FF6200",
      status: "Active",
      courses: 18,
      learners: 1250
    },
    {
      id: "cat-data",
      name: "Data Science",
      slug: "data-science",
      iconType: "emoji",
      icon: "📊",
      imageUrl: "",
      description: "Python, ML, data analysis and visualization.",
      accentColor: "#84117C",
      status: "Active",
      courses: 15,
      learners: 980
    },
    {
      id: "cat-backend",
      name: "Backend Engineering",
      slug: "backend-engineering",
      iconType: "emoji",
      icon: "🧩",
      imageUrl: "",
      description: "Java, Spring Boot, Node.js, REST APIs.",
      accentColor: "#6C1D5F",
      status: "Active",
      courses: 21,
      learners: 1560
    },
    {
      id: "cat-design",
      name: "UI/UX Design",
      slug: "ui-ux-design",
      iconType: "emoji",
      icon: "🎨",
      imageUrl: "",
      description: "Figma, design systems, user research.",
      accentColor: "#793B74",
      status: "Inactive",
      courses: 9,
      learners: 670
    },
    {
      id: "cat-security",
      name: "Security",
      slug: "security",
      iconType: "emoji",
      icon: "🔐",
      imageUrl: "",
      description: "Cybersecurity, OWASP, ethical hacking.",
      accentColor: "#4A1E47",
      status: "Active",
      courses: 7,
      learners: 430
    },
    {
      id: "cat-mobile",
      name: "Mobile Development",
      slug: "mobile-development",
      iconType: "emoji",
      icon: "📱",
      imageUrl: "",
      description: "React Native, Flutter, iOS, Android.",
      accentColor: "#5C4F61",
      status: "Active",
      courses: 11,
      learners: 790
    },
    {
      id: "cat-ai",
      name: "AI & Machine Learning",
      slug: "ai-machine-learning",
      iconType: "emoji",
      icon: "🤖",
      imageUrl: "",
      description: "LLMs, neural networks, model training.",
      accentColor: "#01AC9F",
      status: "Inactive",
      courses: 6,
      learners: 520
    },
    {
      id: "cat-architecture",
      name: "Architecture",
      slug: "architecture",
      iconType: "emoji",
      icon: "🏛️",
      imageUrl: "",
      description: "Microservices, API gateways, CQRS and distributed systems.",
      accentColor: "#91759E",
      status: "Active",
      courses: 4,
      learners: 315
    }
  ],
  courses: [
    {
      id: "course-spring",
      title: "Spring Boot Masterclass",
      slug: "spring-boot-masterclass",
      categoryId: "cat-backend",
      level: "Intermediate",
      language: "English",
      duration: "18 hrs",
      shortDescription: "Master Spring Boot and build production-ready REST APIs from scratch.",
      description: "A hands-on backend engineering course covering Spring Boot fundamentals, REST APIs, persistence, security, deployment and production readiness.",
      icon: "☕",
      thumbnail: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
      bannerImage: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1400&q=80",
      youtubeVideoUrl: "https://youtube.com/watch?v=spring",
      previewVideoUrl: "",
      learningOutcomes: ["Build REST APIs with Spring Boot", "Understand dependency injection and IoC", "Deploy microservices to the cloud"],
      prerequisites: ["Basic Java knowledge", "Familiarity with Maven/Gradle"],
      targetAudience: ["Java developers wanting to learn Spring", "Backend engineers modernising their stack"],
      courseHighlights: "Production-grade patterns, layered architecture, validation, testing and deployment checklists.",
      careerOpportunities: "Backend developer, Java engineer, API developer, microservices engineer.",
      isActive: true,
      isPublished: true,
      isFeatured: true,
      allowIndexing: true,
      showInSearch: true,
      metaTitle: "Spring Boot Masterclass | Xebia Learning",
      metaDescription: "Master Spring Boot and build production-ready REST APIs. Covers DI, Spring Security, microservices and cloud deployment.",
      canonicalUrl: "https://xebia.com/courses/spring-boot-masterclass",
      robots: "index, follow",
      author: "Ankit Sharma",
      seoCategory: "Backend Development",
      metaKeywords: "spring boot, java, rest api, microservices",
      seoTags: "backend, java, spring, api, cloud",
      primaryKeyword: "spring boot course",
      secondaryKeywords: "learn spring boot, spring boot tutorial",
      focusKeywords: "spring boot masterclass, java backend",
      semanticKeywords: "dependency injection, ioc container, spring mvc",
      searchIntent: "informational, transactional",
      relatedTopics: "Java EE, REST API design, Docker, Kubernetes",
      ogTitle: "Spring Boot Masterclass",
      ogDescription: "Build production-ready backend APIs with Spring Boot.",
      ogImage: "",
      twitterTitle: "Spring Boot Masterclass",
      twitterDescription: "A practical Spring Boot course for backend developers.",
      faqContent: "Q: Who is this course for? A: Java developers wanting to modernise their backend skills.",
      customHeadScript: "",
      customBodyScript: ""
    },
    {
      id: "course-react",
      title: "React & TypeScript Deep Dive",
      slug: "react-typescript-deep-dive",
      categoryId: "cat-web",
      level: "Advanced",
      language: "English",
      duration: "14 hrs",
      shortDescription: "Build scalable product interfaces with modern React and TypeScript.",
      description: "Component architecture, state modeling, hooks, accessibility, routing, form design and performance profiling.",
      icon: "⚛️",
      thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80",
      bannerImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1400&q=80",
      youtubeVideoUrl: "",
      previewVideoUrl: "",
      learningOutcomes: ["Model complex UI state", "Compose accessible components", "Profile and optimize React screens"],
      prerequisites: ["JavaScript fundamentals", "React basics"],
      targetAudience: ["Frontend engineers", "UI engineers"],
      courseHighlights: "Real-world app architecture, reusable patterns, reviewable UI decisions.",
      careerOpportunities: "Frontend engineer, product engineer, React specialist.",
      isActive: true,
      isPublished: true,
      isFeatured: false,
      allowIndexing: true,
      showInSearch: true,
      metaTitle: "React & TypeScript Deep Dive | Xebia Learning",
      metaDescription: "Advance your React skills with TypeScript, accessibility, performance and state modeling.",
      canonicalUrl: "",
      robots: "index, follow",
      author: "Priya Menon",
      seoCategory: "Frontend",
      metaKeywords: "react, typescript, frontend",
      seoTags: "react, ui, frontend",
      primaryKeyword: "advanced react course",
      secondaryKeywords: "",
      focusKeywords: "",
      semanticKeywords: "",
      searchIntent: "informational",
      relatedTopics: "Design systems, accessibility",
      ogTitle: "React & TypeScript Deep Dive",
      ogDescription: "",
      ogImage: "",
      twitterTitle: "",
      twitterDescription: "",
      faqContent: "",
      customHeadScript: "",
      customBodyScript: ""
    },
    {
      id: "course-python",
      title: "Python Data Science Bootcamp",
      slug: "python-data-science-bootcamp",
      categoryId: "cat-data",
      level: "Beginner",
      language: "English",
      duration: "30 hrs",
      shortDescription: "Python, notebooks, analysis, charts and first machine-learning models.",
      description: "A complete path from Python basics to practical analysis and model building.",
      icon: "🐍",
      thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
      bannerImage: "",
      youtubeVideoUrl: "",
      previewVideoUrl: "",
      learningOutcomes: ["Clean and analyze data", "Create visual dashboards", "Train basic ML models"],
      prerequisites: ["No prior data experience needed"],
      targetAudience: ["Analysts", "Career switchers", "Engineers"],
      courseHighlights: "Notebook labs, charting, project portfolio.",
      careerOpportunities: "Data analyst, junior data scientist.",
      isActive: true,
      isPublished: true,
      isFeatured: false,
      allowIndexing: true,
      showInSearch: true,
      metaTitle: "Python Data Science Bootcamp",
      metaDescription: "Learn Python for data science with practical projects.",
      canonicalUrl: "",
      robots: "index, follow",
      author: "",
      seoCategory: "Data Science",
      metaKeywords: "python, data science",
      seoTags: "",
      primaryKeyword: "python data science course",
      secondaryKeywords: "",
      focusKeywords: "",
      semanticKeywords: "",
      searchIntent: "informational",
      relatedTopics: "",
      ogTitle: "",
      ogDescription: "",
      ogImage: "",
      twitterTitle: "",
      twitterDescription: "",
      faqContent: "",
      customHeadScript: "",
      customBodyScript: ""
    },
    {
      id: "course-kube",
      title: "Kubernetes for Production",
      slug: "kubernetes-for-production",
      categoryId: "cat-cloud",
      level: "Expert",
      language: "English",
      duration: "22 hrs",
      shortDescription: "Operate Kubernetes clusters with security, observability and deployment discipline.",
      description: "Kubernetes architecture, workloads, Helm, rollout strategies, observability and security hardening.",
      icon: "☸️",
      thumbnail: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&w=1200&q=80",
      bannerImage: "",
      youtubeVideoUrl: "",
      previewVideoUrl: "",
      learningOutcomes: ["Deploy production workloads", "Secure clusters", "Observe and debug services"],
      prerequisites: ["Linux basics", "Docker experience"],
      targetAudience: ["DevOps engineers", "Platform teams"],
      courseHighlights: "Production checklists, incident drills, Helm labs.",
      careerOpportunities: "Platform engineer, DevOps engineer, SRE.",
      isActive: false,
      isPublished: false,
      isFeatured: false,
      allowIndexing: false,
      showInSearch: false,
      metaTitle: "Kubernetes for Production",
      metaDescription: "Learn to operate Kubernetes in production.",
      canonicalUrl: "",
      robots: "noindex, nofollow",
      author: "",
      seoCategory: "DevOps",
      metaKeywords: "kubernetes, devops",
      seoTags: "",
      primaryKeyword: "kubernetes production course",
      secondaryKeywords: "",
      focusKeywords: "",
      semanticKeywords: "",
      searchIntent: "",
      relatedTopics: "",
      ogTitle: "",
      ogDescription: "",
      ogImage: "",
      twitterTitle: "",
      twitterDescription: "",
      faqContent: "",
      customHeadScript: "",
      customBodyScript: ""
    },
    {
      id: "course-architecture",
      title: "System Design Fundamentals",
      slug: "system-design-fundamentals",
      categoryId: "cat-architecture",
      level: "Advanced",
      language: "English",
      duration: "10 hrs",
      shortDescription: "API gateways, events, sagas, caching and resilient microservice patterns.",
      description: "A systems course aligned with the LMS architecture brief: gateway, services, events, data ownership and governance.",
      icon: "🏗️",
      thumbnail: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80",
      bannerImage: "",
      youtubeVideoUrl: "",
      previewVideoUrl: "",
      learningOutcomes: ["Design service boundaries", "Model event flows", "Choose reliability patterns"],
      prerequisites: ["Backend fundamentals"],
      targetAudience: ["Engineers", "Architects"],
      courseHighlights: "Architecture maps, scenario tradeoffs, pattern cards.",
      careerOpportunities: "Solution architect, senior engineer.",
      isActive: true,
      isPublished: true,
      isFeatured: false,
      allowIndexing: true,
      showInSearch: true,
      metaTitle: "System Design Fundamentals",
      metaDescription: "Learn practical distributed system design patterns.",
      canonicalUrl: "",
      robots: "index, follow",
      author: "",
      seoCategory: "Architecture",
      metaKeywords: "system design, architecture",
      seoTags: "",
      primaryKeyword: "system design course",
      secondaryKeywords: "",
      focusKeywords: "",
      semanticKeywords: "",
      searchIntent: "",
      relatedTopics: "",
      ogTitle: "",
      ogDescription: "",
      ogImage: "",
      twitterTitle: "",
      twitterDescription: "",
      faqContent: "",
      customHeadScript: "",
      customBodyScript: ""
    },
    {
      id: "course-graphql",
      title: "GraphQL API Development",
      slug: "graphql-api-development",
      categoryId: "cat-backend",
      level: "Intermediate",
      language: "English",
      duration: "9 hrs",
      shortDescription: "Design GraphQL schemas and resolvers for product-grade APIs.",
      description: "Schema design, resolvers, authorization, data loaders and API evolution.",
      icon: "◈",
      thumbnail: "https://images.unsplash.com/photo-1555066932-e78dd8fb77bb?auto=format&fit=crop&w=1200&q=80",
      bannerImage: "",
      youtubeVideoUrl: "",
      previewVideoUrl: "",
      learningOutcomes: ["Create GraphQL schemas", "Build secure resolvers", "Avoid N+1 queries"],
      prerequisites: ["API basics"],
      targetAudience: ["Backend developers"],
      courseHighlights: "Resolver patterns and performance labs.",
      careerOpportunities: "API engineer, backend developer.",
      isActive: true,
      isPublished: false,
      isFeatured: false,
      allowIndexing: true,
      showInSearch: true,
      metaTitle: "GraphQL API Development",
      metaDescription: "Build secure and maintainable GraphQL APIs.",
      canonicalUrl: "",
      robots: "index, follow",
      author: "",
      seoCategory: "Backend",
      metaKeywords: "graphql, api",
      seoTags: "",
      primaryKeyword: "graphql course",
      secondaryKeywords: "",
      focusKeywords: "",
      semanticKeywords: "",
      searchIntent: "",
      relatedTopics: "",
      ogTitle: "",
      ogDescription: "",
      ogImage: "",
      twitterTitle: "",
      twitterDescription: "",
      faqContent: "",
      customHeadScript: "",
      customBodyScript: ""
    }
  ],
  modules: [
    { id: "mod-spring-1", courseId: "course-spring", title: "Introduction to Spring Boot", slug: "introduction-to-spring-boot", description: "Overview of the Spring Boot ecosystem, project setup, and core principles.", order: 1, isActive: true },
    { id: "mod-spring-2", courseId: "course-spring", title: "Dependency Injection & IoC", slug: "dependency-injection-ioc", description: "Understanding the IoC container, bean lifecycle, and DI patterns.", order: 2, isActive: true },
    { id: "mod-spring-3", courseId: "course-spring", title: "Building REST APIs", slug: "building-rest-apis", description: "Creating RESTful endpoints with controllers, services, and repositories.", order: 3, isActive: true },
    { id: "mod-spring-4", courseId: "course-spring", title: "Spring Security & Auth", slug: "spring-security-auth", description: "Implementing JWT authentication and role-based access.", order: 4, isActive: false },
    { id: "mod-react-1", courseId: "course-react", title: "React Architecture", slug: "react-architecture", description: "Component boundaries, routing and state modeling.", order: 1, isActive: true },
    { id: "mod-python-1", courseId: "course-python", title: "Python Analysis Basics", slug: "python-analysis-basics", description: "Dataframes, notebooks, cleaning and charts.", order: 1, isActive: true }
  ],
  submodules: [
    { id: "sub-spring-1", moduleId: "mod-spring-1", title: "What is Spring Boot?", slug: "what-is-spring-boot", description: "History, motivation, and your first project scaffold.", order: 1, isActive: true, metaTitle: "What is Spring Boot?", metaDescription: "A beginner-friendly introduction to Spring Boot.", canonicalUrl: "", ogTitle: "What is Spring Boot?", ogImage: "" },
    { id: "sub-spring-2", moduleId: "mod-spring-1", title: "Project Setup & Structure", slug: "project-setup-structure", description: "Folder layout, pom.xml, application.properties, and DevTools.", order: 2, isActive: true, metaTitle: "", metaDescription: "", canonicalUrl: "", ogTitle: "", ogImage: "" },
    { id: "sub-spring-3", moduleId: "mod-spring-1", title: "Auto-configuration Deep Dive", slug: "auto-configuration", description: "How Spring Boot detects and wires beans automatically.", order: 3, isActive: true, metaTitle: "", metaDescription: "", canonicalUrl: "", ogTitle: "", ogImage: "" },
    { id: "sub-spring-4", moduleId: "mod-spring-1", title: "Running & Debugging", slug: "running-debugging", description: "DevTools, spring profiles, and live-reload workflows.", order: 4, isActive: false, metaTitle: "", metaDescription: "", canonicalUrl: "", ogTitle: "", ogImage: "" },
    { id: "sub-react-1", moduleId: "mod-react-1", title: "State Modeling", slug: "state-modeling", description: "Model state transitions before building UI.", order: 1, isActive: true, metaTitle: "", metaDescription: "", canonicalUrl: "", ogTitle: "", ogImage: "" }
  ],
  contentBlocks: [
    { id: "blk-1", submoduleId: "sub-spring-1", type: "Heading", title: "What is an Array?", text: "What is an Array?", language: "", url: "", caption: "", order: 1, isActive: true },
    { id: "blk-2", submoduleId: "sub-spring-1", type: "Text", title: "Definition", text: "An array is a collection of elements stored at contiguous memory locations. It is the simplest data structure where each item can be accessed by index.", language: "", url: "", caption: "", order: 2, isActive: true },
    { id: "blk-3", submoduleId: "sub-spring-1", type: "Callout", title: "Key insight", text: "Arrays offer O(1) random access but O(n) insertion/deletion at arbitrary positions.", language: "", url: "", caption: "", order: 3, isActive: true },
    { id: "blk-4", submoduleId: "sub-spring-1", type: "Code", title: "Java array sample", text: "int[] arr = {1, 2, 3, 4, 5};\nSystem.out.println(arr[0]);", language: "Java", url: "", caption: "", order: 4, isActive: true },
    { id: "blk-5", submoduleId: "sub-spring-1", type: "Image", title: "Memory layout", text: "", language: "", url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80", caption: "Memory layout diagram for arrays", order: 5, isActive: true },
    { id: "blk-6", submoduleId: "sub-spring-1", type: "Video", title: "Array walkthrough", text: "", language: "", url: "https://www.youtube.com/watch?v=example", caption: "", order: 6, isActive: true },
    { id: "blk-7", submoduleId: "sub-spring-1", type: "Table", title: "Complexity table", text: "| Operation | Time |\n| --- | --- |\n| Access | O(1) |\n| Insert | O(n) |", language: "", url: "", caption: "", order: 7, isActive: true },
    { id: "blk-8", submoduleId: "sub-spring-2", type: "Notes", title: "Setup checklist", text: "Install JDK, create a Spring Initializr project, open it in your IDE and run the generated application class.", language: "", url: "", caption: "", order: 1, isActive: true }
  ],
  audit: [
    { id: "aud-1", label: "Category created", target: "Web Development", time: "Just now" },
    { id: "aud-2", label: "Course published", target: "Spring Boot Masterclass", time: "Today" },
    { id: "aud-3", label: "Submodule updated", target: "Project Setup & Structure", time: "Yesterday" }
  ]
};
